#
/control/verbose 1
/control/saveHistory
#
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
# 
#
/gun/particle gamma
/BH/gun/set_gamma_mode true
/BH/gun/set_central_energy 60 MeV
/BH/gun/set_delta_min -0.
/BH/gun/set_delta_max +0.
/BH/gun/set_radius_max 0.65 cm
/BH/gun/set_x_min -0.65 cm
/BH/gun/set_x_max 0.65 cm
/BH/gun/set_y_min -0.65 cm
/BH/gun/set_y_max 0.65 cm
/BH/gun/set_angle_max 175 mrad
/BH/gun/set_theta_min -0 mrad
/BH/gun/set_theta_max 0 mrad
/BH/gun/set_phi_min -0 mrad
/BH/gun/set_phi_max 0 mrad
/BH/detector/set_target_thickness 0.025 mm
/BH/detector/set_target_material G4_U # Uranium
/BH/detector/update
/BH/detector/print
/BH/gun/print
/BH/outputfile/set_use_monitor true
/BH/outputfile/set_use_unique_filename true
/run/beamOn 2000000
/run/beamOn 2000000
/run/beamOn 2000000
